version: "3.0"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=britecore
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "8010:8010"
    depends_on:
      - db